### ISSUE TITLE
Profile displaying twice

### ISSUE THREAD

**Issue by davaayy** [motzel/ScoreSaberCountryLeaderboard#109] opened 2021-09-29 09:18 UTC
**Describe the bug**
In the top tab, my user profile shows up twice, there are also 2 friends tabs, and whenever I click on a map, the leaderboard shows up twice as well, with the top one saying "undefined" in the map decription window

**To Reproduce**
No Idea. Never did anything to the extension, I am on Microsoft Edge, but when I imported my backup into chrome, I saw the same thing, however it was gone upon refresh

**Expected behavior**
Only one of each tab:(

**Screenshots**
![Countryleaderboard](https://user-images.githubusercontent.com/91597101/135240049-5e7bea2d-ae8e-472d-97d8-1a486435a84e.png)

**Please complete the following information:**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Browser version 94.0.992.31

**Additional context**
I think this issue started appearing about a week back. I could be wrong though

**Comment by motzel** [comment] 2021-09-29 10:01
Officially the project is no longer supported, but I took a look at it. I'm not able to reproduce it on the exact same version of the browser.

But I see that Umbra added something called Rocket Loader managing the javascript loading and this is probably the reason for this behavior. Judging by your screenshot my userscript is running twice because I see a double avatar with a flag on the navbar.

Could you press F12 and in the dev console check if you see the duplicated "[ScoreSaber country leaderboard] init" message?

**Comment by motzel** [comment] 2021-09-29 10:14
I just released version 1.8.4 with protection against double initialization of the script. Did it solve your problem?

**Comment by motzel** [comment] 2021-09-29 10:23
And by the way... I encourage you to try https://ssr.motzel.dev It doesn't support all the features of this userscript yet, but it has some cool new features 😁

**Comment by davaayy** [comment] 2021-09-29 10:24
It did! Thanks a lot! Would you still like the screenshot?

**Comment by motzel** [comment] 2021-09-29 10:28
Since it's working I'm closing the issue. I'm glad it solved your problem 😁

**Closed as completed by motzel** 2021-09-29 10:28 UTC
Labels: bug
